try {
    // dangerous Code with throw
} catch (someType someName) {
    // some error handling.
}
// normal execution continues here